model: "meta-llama/Llama-2-7b-hf"
finetune_model: "Llama-2-7b-hf_text_2"
epoch: 8
learning_rate: 0.00001
batch_size: 4
max_token: 1
add_text: True
claim_max_len: 100
evidence_max_len: 1000
add_qa: False
add_q: False
add_a: False
question_max_len: 50
claim_answer_max_len: 25
evidence_answer_max_len: 25