model: "microsoft/deberta-v3-large"
finetune_model: "deberta-v3-large_qa_text_1"
epoch: 8
learning_rate: 0.00001
batch_size: 4
max_token: 650
add_text: True
claim_max_len: 100
evidence_max_len: 1000
add_qa: True
add_q: True
add_a: True
question_max_len: 50
claim_answer_max_len: 25
evidence_answer_max_len: 25