model: "facebook/opt-1.3b"
finetune_model: "opt-1.3b_text_1"
epoch: 8
learning_rate: 0.00001
batch_size: 1
max_token: 10
add_text: True
claim_max_len: 50
evidence_max_len: 100
add_qa: False
add_q: False
add_a: False
question_max_len: 50
claim_answer_max_len: 25
evidence_answer_max_len: 25