model: "microsoft/deberta-v3-large"
finetune_model: "deberta-v3-large_text_3"
epoch: 8
learning_rate: 0.00002
batch_size: 4
max_token: 650
claim_max_len: 200
evidence_max_len: 2000
add_qa: False
add_q: False
add_a: False
question_max_len: 100
claim_answer_max_len: 50
evidence_answer_max_len: 50