batch_size: 24
best_epoch: 10
best_val_accurancy: 0.75244
best_val_avg: 0.7495499999999999
best_val_f1: 0.74666
classifier_weight: 0.5
device: '1'
different_classifier: true
dropout: 0.1
epochs: 15
eval_per_epochs: 1
feature_embedding_len: 32
features_num: 65
freeze_text: 1
gpu: true
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_len: 3200
max_sequence_length: 512
output_folder_name: ./model/20231124-202043_deberta-v3-large_features_-1~1_dc/
pretrained_text: microsoft/deberta-v3-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
text_model_gpu: true
total_loss: 124.60621403157711
use_dataset: features_-1~1
use_features: true
val_accurancy: 0.74356
val_f1: 0.74001
