batch_size: 24
device: '1'
dropout: 0.1
epochs: 15
eval_per_epochs: 1
feature_embedding_len: 16
features_num: 65
freeze_text: 1
gpu: true
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_len: 3200
max_sequence_length: 512
output_folder_name: ./model/20231124-040148_deberta-v3-large_features_0~1_fel-16/
pretrained_text: microsoft/deberta-v3-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
text_model_gpu: true
total_loss: 395.7290092408657
use_dataset: features_0~1
use_features: true
val_accurancy: 0.63511
val_f1: 0.60428
