batch_size: 24
device: '1'
dropout: 0.1
epochs: 15
eval_per_epochs: 1
freeze_text: 1
gpu: true
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_len: 3200
max_sequence_length: 512
output_folder_name: ./model/20231123-113555_deberta-v3-base/
pretrained_text: microsoft/deberta-v3-base
qa_dim: 768
seed_value: 42
text_dim: 768
text_model_gpu: true
total_loss: 397.7930557131767
val_accurancy: 0.61911
val_f1: 0.53494
