batch_size: 24
best_val_accurancy: 0.74978
best_val_f1: 0.74774
device: '1'
dropout: 0.1
epochs: 20
eval_per_epochs: 1
freeze_text: 1
gpu: true
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_sequence_length: 512
output_folder_name: ./model/20231109-231113_deberta-large/
pretrained_text: microsoft/deberta-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
text_model_gpu: true
total_loss: 4.233608559850836
val_accurancy: 0.73111
val_f1: 0.731
