batch_size: 24
best_val_accurancy: 0.74444
best_val_f1: 0.73632
device: '1'
dropout: 0.1
epochs: 20
eval_per_epochs: 1
freeze_image: 1
freeze_text: 1
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_sequence_length: 512
output_folder_name: ./model/20231031-215010_text_qa_5/
pretrained_image: microsoft/swinv2-base-patch4-window8-256
pretrained_text: microsoft/deberta-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
total_loss: 3.454571470123483
