batch_size: 24
device: '1'
dropout: 0.1
epochs: 30
eval_per_epochs: 1
freeze_text: 1
gpu: true
head: 2
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_sequence_length: 512
output_folder_name: ./model/20231107-003140_gpt2/
pretrained_text: gpt2
qa_dim: 768
seed_value: 42
text_dim: 768
text_model_gpu: true
val_accurancy: 0.676
val_f1: 0.66945
