batch_size: 24
best_val_accurancy: 0.74267
best_val_f1: 0.73853
device: '1'
dropout: 0.1
epochs: 15
eval_per_epochs: 1
freeze_text: 1
gpu: true
head: 8
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_sequence_length: 512
output_folder_name: ./model/20231114-042925_deberta-large_h-8/
pretrained_text: microsoft/deberta-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
text_model_gpu: true
total_loss: 99.0608757212758
val_accurancy: 0.73689
val_f1: 0.73596
