batch_size: 24
best_val_accurancy: 0.74933
best_val_f1: 0.74358
device: '1'
dropout: 0.1
epochs: 15
eval_per_epochs: 1
freeze_text: 1
gpu: true
head: 4
hidden_dim: 256
loss_weight: 0.7
lr: 5.0e-05
max_sequence_length: 512
output_folder_name: ./model/20231113-224314_deberta-large_h-4/
pretrained_text: microsoft/deberta-large
qa_dim: 1024
seed_value: 42
text_dim: 1024
text_model_gpu: true
total_loss: 204.0226255506277
val_accurancy: 0.74933
val_f1: 0.74358
