mode: "val"
model: "microsoft/deberta-v3-large"
finetune_model: "finetune/microsoft/deberta-v3-large_2"
device: "cuda"
epoch: 6
batch_size: 4
max_len: 32000
is_finetune_model: True
max_order: 1
learning_rate: 0.00001